### PR TITLE
added required files for automation

### PR DESCRIPTION
**Pull request by Simon-Percy**
I hope you're doing well. I wanted to share some exciting updates related to your tutorial on deploying a Vite React app to GitHub. Your video has been immensely helpful, and after spending three weeks on creating different react projects, I found an opportunity to enhance the workflow.

In an effort to streamline deployment, I've created a batch script that automates the addition of necessary files. Now, with a simple command, the required files are automatically generated. Additionally, I've set up a VS Code task to open and run the script seamlessly.

I believe these changes will contribute to a smoother deployment experience and save time for anyone, you can even make a video about it.

I'm submitting this pull request with the hope that these enhancements can be considered for inclusion. Your guidance has been invaluable, and I'm eager to contribute back to the community.

Thank you for your time and consideration.

### CODE REVIEW

**Comment by ErickKS** [comment]
Hi @Simon-Percy, this automation is excellent, I'm glad you shared it here! 

However, unfortunately, I can't make changes to the main branch. This is because this "guide" project is in a YouTube video, and it wouldn't be very intuitive for me to add something that I did not show there.

By the way, this automation is really very good. It speeds up the development process significantly, especially in the `.yml` file part, which is the most annoying part of the process.

I'll try to give your pull request a special mention in the `readme.md`

**Comment by Simon-Percy** [comment]
No worries at all! I thought a pull request would be the best way to get in touch. I completely understand the context of the guide project being part of a YouTube video.

Your guidance has been invaluable, and I appreciate your kind words about the automation.

Thank you for your continued education and sharing of knowledge. It's truly amazing. Looking forward to more of your content.

And thanks a lot for considering a special mention in the README.md for the pull request.!

**Comment by Simon-Percy** [comment]
"Hey @ErickKS,

I noticed a lack of guidance on using the batch file, especially with VSCode tasks. So, I've created a new repository with a detailed README explaining how these files work and referenced your video and repository for additional help. Your thoughts on this would be great!

Thank you for your time.

**Comment by MohammedKhred7** [comment]
don't using build with deploy ?? why

**Comment by ProAbdallaMI** [comment]
these files is only for windows users but not linux

**Pull request closed without merging**
